name: PR Test

on: 
  pull_request:
    branches: ['main', 'develop']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to this repository
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
      - name: Install dependencies from lock file
        run: yarn
      - name: Run test
        run: yarn test
